language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script: 
  - python -m unittest discover tests/
  - coverage run --source=pyrandimg -m py.test
after_success:
  - coveralls
sudo: false
